# integrate ipeos/spip + mariadb + create network (based on wordpress)

version: '3'
services:
  spip:
    image: ipeos/spip:latest
    environment:
      - PHP_TIMEZONE=Europe/Paris
      - LANG='fr_FR.UTF-8'
      - SPIP_DB_PASS=spippassword
    ports:
      - 9000:80
    links:
      - mariadb:mysql
    volumes:
      - ./src/IMG:/var/www/html/IMG:rw
      - ./src/squelettes:/var/www/html/squelettes:rw
      - ./src/plugins:/var/www/html/plugins:rw
      - ./src/tmp/dump:/var/www/html/tmp/dump:rw
      - ./src/config:/var/www/html/config:rw
      - ./src/ryogasp.htaccess:/var/www/html/.htaccess
    restart: unless-stopped
  mariadb:
    # upgrade: https://mariadb.com/docs/server/service-management/upgrades/community-server/release-series-cs10-6/
    image: mariadb:10.4
    volumes:
      - ./maria/database:/var/lib/mysql
      - ./maria/logs:/var/log/mysql/:rw
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=superrootpassword
      - MYSQL_USER=spip
      - MYSQL_PASSWORD=spippassword
      - MYSQL_DATABASE=spip
    restart: unless-stopped
