#!/bin/sh
# Entrypoint: PHP settings from the environment, SPIP writable directories, wait for MariaDB,
# optional first-run install, then php-fpm + nginx in the foreground.
set -eu

cd /var/www/html

# Any other command runs as-is: `docker run ... spip --version`, `docker run ... sh`
if [ "${1:-serve}" != "serve" ]; then
	exec "$@"
fi

# 1. PHP settings (same PHP_* variables as the previous ipeos/spip image)
cat > /etc/php83/conf.d/99-env.ini <<INI
; generated by docker-entrypoint.sh from PHP_* environment variables
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
memory_limit = ${PHP_MEMORY_LIMIT}
post_max_size = ${PHP_POST_MAX_SIZE}
upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}
date.timezone = ${PHP_TIMEZONE}
INI

# 2. Directories SPIP writes to. tmp/ and local/ are volumes (empty on first run).
#    IMG/, config/, plugins/, squelettes/ are bind mounts: owner must match SPIP_UID (see readme).
mkdir -p tmp/dump tmp/log tmp/upload local lib plugins/auto
find tmp local lib -maxdepth 1 ! -user www-data -exec chown www-data:www-data {} + 2>/dev/null || true

# SPIP >= 4.4 cannot boot without config/spip/{dirs,routes}.php (they ship with the core
# but the mounted config/ hides them; ryogasp tracks them in src/config/spip)
if [ ! -d config/spip ]; then
	cp -a /usr/local/share/spip-config-spip config/spip
	chown -R www-data:www-data config/spip
	echo "restored missing config/spip/ from the SPIP core defaults"
fi

# 3. Wait for the database
if [ "${SPIP_DB_SERVER}" = "mysql" ]; then
	until nc -z -w 2 "${SPIP_DB_HOST}" 3306; do
		echo "waiting for database ${SPIP_DB_HOST}:3306 ..."
		sleep 2
	done
fi

# 4. No config yet: install SPIP (same behaviour as the previous image; ryogasp mounts src/config)
if [ ! -e config/connect.php ] && [ "${SPIP_AUTO_INSTALL}" = "1" ]; then
	spip install \
		--db-server "${SPIP_DB_SERVER}" --db-host "${SPIP_DB_HOST}" \
		--db-login "${SPIP_DB_LOGIN}" --db-pass "${SPIP_DB_PASS}" \
		--db-database "${SPIP_DB_NAME}" --db-prefix "${SPIP_DB_PREFIX}" \
		--adresse-site "${SPIP_SITE_ADDRESS}" \
		--admin-nom "${SPIP_ADMIN_NAME}" --admin-login "${SPIP_ADMIN_LOGIN}" \
		--admin-email "${SPIP_ADMIN_EMAIL}" --admin-pass "${SPIP_ADMIN_PASS}" || true
fi

# 5. Default mes_options.php, as the previous image did
if [ ! -e config/mes_options.php ]; then
	cat > config/mes_options.php <<'PHP'
<?php
if (!defined("_ECRIRE_INC_VERSION")) return;
$GLOBALS['spip_header_silencieux'] = 1;
PHP
	chown www-data:www-data config/mes_options.php
fi

# 6. Both servers in the foreground; leave as soon as one dies so Docker restarts the container.
#    nginx only starts once php-fpm listens, otherwise the first requests get a 502.
php-fpm83 --nodaemonize --fpm-config /etc/php83/php-fpm.conf &
FPM=$!
i=0
while [ ! -S /run/php-fpm.sock ] && [ $i -lt 50 ]; do
	sleep 0.2
	i=$((i + 1))
done
nginx -g 'daemon off;' &
NGX=$!
trap 'kill -TERM $FPM $NGX 2>/dev/null' TERM INT

status=0
wait -n || status=$?
kill -TERM $FPM $NGX 2>/dev/null || true
wait
exit $status
